apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-depl
  labels:
    app: flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: aman3105/flask-nfm
        env:
        - name: FLASK_SERVER_PORT
          value: "9091"
