name: Run ci-cd pipeline
on: 
    push

jobs:
    docker-compose:
        runs-on: self-hosted
        steps:
        -   name: Checkout repo
            uses: actions/checkout@v4
                
        # -   name: change directory
        #     run: cd flask-redis

        -   name: Login to Docker Hub
            uses: docker/login-action@v3
            with:
                username: aman3105
                password: dOC@MAN3105

        -   name: Build and push
            uses: docker/build-push-action@v5
            with:
                push: true
                context: ./flask
                tags: aman3105/flask-nfm

        # -   name: Execute docker compose
        #     run: |
        #         cd flask-redis
        #         docker compose up -d